### ISSUE TITLE
Suugestions: Frameshops and Chat messages.

### ISSUE THREAD

**Issue by Blackyvk** [RegalOwl/HyperConomy#100]
I had  a problem and you tweaked it and I think it improved in general but, I still can get the tps down if i use the frames indefinitely.

So why not change the way frameshops work or add a new option.... When you click (left/right) instead of instantly sell/buy you must type in chat the amount you desire, some people in my server dont realize there are signs where you can sell in stacks, so they sell 20 stacks of cobblestone 1 by 1 using frameshops, if they get this chat thing, it could be easier and less heavy on resources I believe. Of course, I think some servers would still prefer use the frameshops directly, so a toggle in the config could solve this. I use framehops mostly to show people the item and the price nothing else, since signs take more space to do that.

I also once  suggested lessen the chat spam by switching to action bar messages toggle able as well, it could be a nice feature, since those don't take space and just dissapear.

**Comment by RegalOwl** [comment]
The performance should be significantly better in the latest builds, so this shouldn't be an issue any longer.  Let me know if it is.
