### ISSUE TITLE
Could not pass event PlayerDropItemEvent

### ISSUE THREAD

**Issue by Blackyvk** [RegalOwl/HyperConomy#102]
http://pastebin.com/tSLbHYm0

It's caused by potions or bottles with different name or lore i believe, i thought it was the plugin brewery but I edited lore and name of a water bottle and the error  showed up

**Comment by RegalOwl** [comment]
Unfortunately this is because you're running Spigot 1.8.  You'll need to use an older build of HyperConomy or upgrade to 1.9 to get rid of this error.  I had to use some new methods in 1.9 to support new features.
