### ISSUE TITLE
Items Bought Go To Armor Slots

### ISSUE THREAD

**Issue by Artige** [RegalOwl/HyperConomy#104]
On 1.9.4, items bought while a player's inventory is full will be placed into their armor slot, effectively allowing the player to wear items.

Plugin version: hyperconomy-0.975.7
Server version:Paper version git-Paper-754 (MC: 1.9.4) (Implementing API version 1.9.4-R0.1-SNAPSHOT)

**Comment by RegalOwl** [comment]
Sorry for the delay, busy summer.  This is fixed in the latest dev build.
