### ISSUE TITLE
[URGENT] Wood Types Not Compositing

### ISSUE THREAD

**Issue by Artige** [RegalOwl/HyperConomy#106]
For some reason only oak wood will composite when factoring in prices for items like sticks. Other wood types do not composite.

Hyperconomy 0.975.7 running on 1.9.4 Paper Spigot Build 768

**Comment by RegalOwl** [comment]
There is only one type of stick, and no way to know which type of wood it originated from without a lot of unnecessary work, so any generic wood item composites to oak wood.  There isn't really any other way to do it, except for just making them not composites.  Let me know if you have a better idea.
