### ISSUE TITLE
Hyperconomy configuration constant default bug

### ISSUE THREAD

**Issue by Flyerminer** [RegalOwl/HyperConomy#116]
I'm running a server using no other plugins, and the only plugins in the folder are Hyperconomy and Vault. If I change any setting in the config.yml, save it, and restart/reload the server, it immediately reverts all changes done to the configuration file back to the default config. I hope this can be corrected! Thank you!

**Comment by remremrem** [comment]
You must edit the config.yml file while the server is off, then start the server.
