### ISSUE TITLE
How to set different buy and sell prices for each items in server shop

### ISSUE THREAD

**Issue by scorpioservo** [RegalOwl/HyperConomy#118]
Hello, I am trying to customize both the buy and sell price for each item in the server shops. I haven't figured out a way to do so. I have looked all over the wiki and FAQ. How do I do this?

**Comment by RegalOwl** [comment]
This can't be done currently.  You could use a tax, but it's not really the same thing.  Use a player shop instead.  I will merge player shops with server shops in the future to make it less confusing.  For now a player shop with the /ms stockmode toggle is the best way, as it will use the economy's stock levels for the player shop and make it act like a server shop.
