### ISSUE TITLE
Arbitrary text entered in chest shop sign causes rows to be created in players table

### ISSUE THREAD

**Issue by mb243** [RegalOwl/HyperConomy#122]
I have found that when players create a chest shop sign with any arbitrary text in the bottom two rows, a row is created in the `players` table in MySQL with UUID set to NULL and the balance is set to default. I don't believe this is intended behavior. 

Screenshot of the created db rows:
<img width="607" alt="screen shot 2017-03-10 at 7 24 59 am" src="https://cloud.githubusercontent.com/assets/9483554/23795289/bda29dfc-0562-11e7-9566-0fb5768029b8.png">

**Comment by RegalOwl** [comment]
I have a complete rewrite of the chest shops almost ready.  The new chest shops will solve this issue.

**Comment by RegalOwl** [comment]
The new chest shops are available.
