### ISSUE TITLE
[hc-dev] Numerous issues with banks

### ISSUE THREAD

**Issue by mb243** [RegalOwl/HyperConomy#123]
When using /hcbank commands from the hc-dev branch, I've noticed a few oddities:

- Creating a new bank and depositing and withdrawing money work as expected, but
- Deleting the bank does not work (Bank is still shown in '/hcbank top', etc)
- The `hyperconomy_banks` table is empty, as is the banks CSV created from `hcdata exportcsv all`, so I'm not entirely sure where the data is being stored :)

**Comment by RegalOwl** [comment]
Sorry this took so long.  This is fixed.  Virtually all HyperConomy data is stored in RAM for performance reasons while the server is running.  The RAM objects for the banks weren't being properly cleared.
