### ISSUE TITLE
Plugin returning outdated even though its updated

### ISSUE THREAD

**Issue by Robbinho15** [RegalOwl/HyperConomy#126]
Commands are not returning anything in game/console

Enabling / disabling the plugin through pluginmanager yields these errors on spigot 1.11

https://gyazo.com/8507c90c9658da0f8a1725d8afa59d35

**Comment by RegalOwl** [comment]
Check if there is a HyperConomy error when you're starting your server.  I can't see much from that error, unfortunately.

**Comment by RegalOwl** [comment]
There should be an error during startup if you look back through your server log.  I can't see much from that error except that HyperConomy didn't load properly.

**Comment by RegalOwl** [comment]
Please comment and reopen this if you have more information.  I can't fix this or reproduce it without more information.
