### ISSUE TITLE
Chestshop not showing GUI (when the chest even opens)

### ISSUE THREAD

**Issue by ResqDiver1317** [RegalOwl/HyperConomy#127]
We updated a couple days ago to MC 1.12 and updated to the latest HC version. I setup a new chest and put the sign with chestshop on it. The sign changes to the light blue text and sometimes, it will let me open the chest. When I do open the chest, there is no GUI showing, it's just a normal chest. Once i've opened it once, it will not let me open it again unless I hold shift and break the sign. I tried with and without using /hccs setowner to set me as the owner of the chestshop.

**Comment by RegalOwl** [comment]
Are you running Spigot?  Getting any error messages in your HyperConomy folder or in the server log?

**Comment by ResqDiver1317** [comment]
We are running Spigot (CraftBukkit version git-Spigot-cd6ba67-2a2d6d6 (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT). I just double checked the logs and did not see any errors at all related to Hyperconomy and no errors showing in the hyperconomy folder either.

**Comment by ResqDiver1317** [comment]
I have zipped up my HC folder and put our latest.log file in it as well and put it in my dropbox in case that will be of any help to you. 

https://www.dropbox.com/s/atfa5rf6c1g4uwv/HyperConomy.zip?dl=1

**Comment by RegalOwl** [comment]
Yes, that's very helpful.  I'll take a look.

**Comment by RegalOwl** [comment]
This should be fixed in the latest dev build: http://regalowl.net:8080/job/HyperConomy/12/  Let me know if you run into any other issues or still have problems with this.  

The issue was that your default economy didn't have some of the items that the chest shops use for icons.  The chest shops now reference the "base" economy instead which contains all the default HyperConomy items.

**Comment by ResqDiver1317** [comment]
So i just need to update to this new snapshot and it should be good?

**Comment by ResqDiver1317** [comment]
Sweet!! Just tested it and it looks like we are in business!!! Thanks for your help!

**Comment by RegalOwl** [comment]
No problem!
