### ISSUE TITLE
Allows items to have illegal enchantments purchased

### ISSUE THREAD

**Issue by mb243** [RegalOwl/HyperConomy#131]
HyperConomy allows a player to purchase an enchantment for an item that it can't legally be applied to. For example, purchasing knockback for an axe. 

IMO, enchantments should be restricted to items that they can legally be applied to as shown on the following page:

http://minecraft.gamepedia.com/Enchanting#Summary_of_enchantments

**Comment by RetroRadical** [comment]
Could i get a reduction on the tax i receive too? 50% is a bit steep :(

**Comment by mb243** [comment]
```
[INFO] This server is running CraftBukkit version git-Spigot-99c2a37-9a82fa7 (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)
[INFO] HyperConomy version 0.975.7
```

**Comment by mb243** [comment]
This is an old issue, does not have recent activity, and I'm not even sure the original issue is valid anymore. Closing this issue to save work for the maintainers.
