### ISSUE TITLE
Accounts should be UUID bound and not Name bound

### ISSUE THREAD

**Issue by Pingger** [RegalOwl/HyperConomy#147]
https://github.com/RegalOwl/HyperConomy/blob/424200b94fd2fb57364a5f36e927ee040e2d480b/src/main/java/regalowl/hyperconomy/account/HyperAccount.java#L5-L14

Minecraft switched over to use UUIDs to allow name changing. For that reason, multiple Players could have the same name and would be using the same HyperAccount.
Therefore HyperAccount should be updated to support UUIDs.
A converter should also be made available, that allows ServerAdmins to transition the Player Accounts to UUID Accounts

**Comment by writeescape** [comment]
not an issue since it stores the UUID in HyperPlayer
