### ISSUE TITLE
TroubleShooting HyperMerchant

### ISSUE THREAD

**Issue by DrkMatr1984** [RegalOwl/HyperConomy#57]
I'm trying to fix some small errors in HyperMerchant on my server and ran across this error when people try to sell things via the HyperMerchant. It looks like a method was removed or replaced in your code for HyperConomy. Can you tell me what this method is replaced by? Thanks! 

11.01 22:05:02 [Server] INFO ... 14 more
11.01 22:05:02 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[custom.jar:git-Spigot-13716d9-0899683]
11.01 22:05:02 [Server] INFO at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_51]
11.01 22:05:02 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_51]
11.01 22:05:02 [Server] INFO at sun.reflect.GeneratedMethodAccessor859.invoke(Unknown Source) ~[?:?]
11.01 22:05:02 [Server] INFO at grokswell.hypermerchant.ShopMenu.onInventoryClick(ShopMenu.java:529) ~[?:?]
11.01 22:05:02 [Server] INFO at grokswell.hypermerchant.ShopMenu.onInventoryClickOrCreative(ShopMenu.java:548) ~[?:?]
11.01 22:05:02 [Server] INFO at grokswell.hypermerchant.ShopMenu.handleMenuItem(ShopMenu.java:500) ~[?:?]
11.01 22:05:02 [Server] INFO at grokswell.hypermerchant.ShopTransactions.Sell(ShopTransactions.java:69) ~[?:?]
11.01 22:05:02 [Server] INFO at grokswell.hypermerchant.ShopTransactions.SellItem(ShopTransactions.java:98) ~[?:?]
11.01 22:05:02 [Server] INFO Caused by: java.lang.NoSuchMethodError: regalowl.hyperconomy.bukkit.BukkitCommon.getSerializableItemStack(Lorg/bukkit/inventory/ItemStack;)Lregalowl/hyperconomy/inventory/HItemStack;

**Comment by remremrem** [comment]
Indeed the method was renamed in HyperConomy. Try the latest build of HyperConomy as the method name has been reverted.

**Comment by DrkMatr1984** [comment]
Thanks!
