### ISSUE TITLE
Feature Suggestion - Stock balancing over time

### ISSUE THREAD

**Issue by MikeGold** [RegalOwl/HyperConomy#61]
I'm running a rather small server with a bunch of very devoted players. One of them told me that if he'll sell about 1000 cookies to the store, the price gets so low, that the further sales are pointless. Since nobody really wants to buy those cookies back, he can't make his living from them. So, is there any chance that if the price of the item hit rock bottom it could go back to basic over time? Maybe the amount of items in the store could also go back to defaults over time? That is my suggestion:
add option go back to default over time, which if enabled would slowly bring the stock values back to defaults over the long time periods (days, weeks). I know that this problem affects only small servers, but it would be really handy.

**Comment by RegalOwl** [comment]
This will be the next major feature I add.  There is already another ticket for this but I'll leave this up for now since it should be added soon.

**Comment by RegalOwl** [comment]
This has been added.
