### ISSUE TITLE
Price history shows a small % decrease even if nothing is bought or sold

### ISSUE THREAD

**Issue by JoeCow** [RegalOwl/HyperConomy#67]
As the title states the price history seems show to a decrease even if the item hasn't been traded at all. This isn't a recent thing. It's been happening for months. You can see the small percentages here on my server store http://joecow.net:7777/The_Black_Cult

**Comment by RegalOwl** [comment]
Thanks for the report.  This should be fixed in the latest dev build.  I'll include the fix in a new release soon.
