### ISSUE TITLE
Possible to sync shops?

### ISSUE THREAD

**Issue by Wilberforce77** [RegalOwl/HyperConomy#68]
Hi, this plugin has a ton of cool features and is exactly what I need for my server except I need help with one thing. In my server, players will collect resources from one world, then build in another (a plot world). They will have separate inventories between the two worlds. I need a shop to be in two different places so that the player can add inventory to the shop in the one world and remove it from the other. I noticed the line "multi-server" in the configuration file. What exactly does this do?

**Comment by RegalOwl** [comment]
Just create 2 shops, one in each world.  As long as they're in the same economy they will access the same stocks and items.

Multi-server mode is mostly for bungeecord setups or multiple server setups where economies, player balances, etc need to be mirrored between multiple servers.

**Comment by Wilberforce77** [comment]
Thank you! This is the plugin I needed!
