### ISSUE TITLE
MySQL connection failed

### ISSUE THREAD

**Issue by jonny42g** [RegalOwl/HyperConomy#70]
http://pastebin.com/q48iNjcm

**Comment by RegalOwl** [comment]
This means you have the wrong username or password in your config.yml for your MySQL database.  Either that or the MySQL server is misconfigured.

**Comment by jonny42g** [comment]
the pass user port db name is correct and how would the server be miss configured and thank you for the help

**Comment by RegalOwl** [comment]
I've tested this again and MySQL is working properly.  Do you have any other applications connecting to the database?  And you're saying .974.57 is able to connect to MySQL using the same credentials that no longer work in the new build?

**Comment by jonny42g** [comment]
found the solution to my problem in config i had to put ' on both side of username and database name

i sall in error.log 
Access denied for user ''@'localhost'
and noticed there is no username there so i added the ' on both sides and then i got database null but username showed up so i was like why not give that ' as well bam no more error and my database works and my old shops are there and can connect to mysql

couldnt tell you why mine needs that maybe the database im connected to i did try 4 other servers with no problem just this one makes me use ' on both sides

sql:
  use-mysql: true
  log-sql-statements: true
  mysql-connection:
    username: '12345'  <--------
    port: 3306
    password: mydbpass
    host: localhost
    database: '12345'  <---------

i hope this can be of some help and i no longer have any errors at this time and wanna say thank you for this wonderful plugin
