### ISSUE TITLE
Support for 1.7.10?

### ISSUE THREAD

**Issue by nicogranelli** [RegalOwl/HyperConomy#74]
I was gathering info to submit a ticket when I realised I have version 0.975.5 installed in a 1.7.10 spigot server. 

What should I do? My server is just starting, and we haven't used HC much, so I can wipe out data without a problem. Should I install a previous version?

**Comment by RegalOwl** [comment]
You'll have to go back to an older build and delete the HyperConomy folder.  You could save a backup if some settings were changed.  Some new features like banners break compatibility with 1.7.10 in the new builds.  I'd recommend v0.974.57 [Beta]; it was a solid build.

**Comment by nicogranelli** [comment]
Thanks for your answer. Finally I will migrate the server to the last spigot version. Should I delete the chest shopts created until now?

**Comment by RegalOwl** [comment]
If you're upgrading there should be no need to delete anything.  HyperConomy, for the most part, can be upgraded without any data loss.
