### ISSUE TITLE
SetStock no longer a commmand

### ISSUE THREAD

**Issue by Samistine** [RegalOwl/HyperConomy#75]
There isn't a way to set stock anymore, what has happened to this plugin...

Yes, I know about the gui, but why remove everything from it that made this plugin hyperconomy

**Comment by RegalOwl** [comment]
[Please check the trade objects commands page.](https://github.com/RegalOwl/HyperConomy-Documentation/blob/master/Wiki/Commands/Trade%20Object%20Management.creole)  All the set commands were bundled together under the /hcset command quite a while ago.  To change stock use /hcs stock [object] [new stock]
