### ISSUE TITLE
Shops.yml gone

### ISSUE THREAD

**Issue by Samistine** [RegalOwl/HyperConomy#76]
There is no longer shops.yml, as such I can no longer set s1 and s2 via a file.

**Comment by Samistine** [comment]
Had to manually edit the sqlite file. I guess its easy enough to do.

**Comment by Samistine** [comment]
![Image](http://i.imgur.com/3UQw9Zn.png)

**Comment by RegalOwl** [comment]
All HyperConomy data has been moved to the database with the exception of language files and the config.  You can still relatively easily edit any of the data using an Excel type program.  Just export the database to CSV files with /hcdata exportcsv all.  After that edit the CSV file data in the HyperConomy\import_export folder.  Just make sure that the editor doesn't change the CSV format.  After you're finished editing reimport the data with /hcdata importcsv all.  This will update the database with the modified data.
