### ISSUE TITLE
Updating to 1.8.

### ISSUE THREAD

**Issue by GuiMaster** [RegalOwl/HyperConomy#78]
Hello, Some questions about HyperConomy : 

I have a 1.7.10 server with some custom prices, with updating to 1.8 : 
- Will i lose my prices ?
- Will it add the new 1.8 objects/composites ?

Where can I find the new table prices for 1.8 ?

Thanks

**Comment by RegalOwl** [comment]
The best way to update is to make a copy of your HyperConomy folder as a backup.  Generally the upgrades should be safe and not cause any data loss but it's best to be safe.  After a backup of the folder is made place the new version of HyperConomy.jar into your plugins folder and start the server.  Make sure everything was upgraded properly before deleting the backup.

To add the new items after upgrading use the command /hcdata importmissing [name of your economy].  If you haven't made any additional economies you can just run /hcdata importmissing.  If you do have multiple economies run the command for each economy.

**Comment by GuiMaster** [comment]
Awesome ! Thanks.
