### ISSUE TITLE
List of given commands are not working in 1.8.1

### ISSUE THREAD

**Issue by The43thAlpha** [RegalOwl/HyperConomy#81]
So, i'm running a spigot 1.8.1 server and most of the commands given on Dev.Bukkit.org
in Commands, bunch of them are not working.

so i wonder if it you that may not have made the changes there or if those commands were taken off the plugin, because i'm actualy disapointed to see them there if they don't work at all on my server.

**Comment by RegalOwl** [comment]
Could you list the commands you're having trouble with or link to the page with the commands?  There is an old commands page which isn't linked to from anywhere just for people who have very old versions of HyperConomy still on Bukkit.  Other than that everything should be working.  The commands page was switched a long time ago.

**Comment by The43thAlpha** [comment]
Actually i found out myself that you changed them, maybe you should update the list...

Most of them have "/hc" added right before the given commands, thats why

Ps: this plugin is really useful. I passed from a ugly item frames with SignShops under them
to a nice Villager Market
