### ISSUE TITLE
Adding new items

### ISSUE THREAD

**Issue by wookiefever** [RegalOwl/HyperConomy#84]
When I try to add new items by using the hyperconomy gui the items get added to the list. However in game if I go /importnewitems [economy] it says that the command is not recognized. Also if I try to add items from within the game it says the command is not recognized.

I need to add the ores from thermal expansion. Help please.

Using minecraft 1.7.10
with the latest hyperconomy

**Comment by wookiefever** [comment]
@RegalOwl any ideas?

**Comment by RegalOwl** [comment]
The command is now /additem [name] [value] while you're holding the item you'd like to add.
