### ISSUE TITLE
Overflow Error Post Initialization

### ISSUE THREAD

**Issue by jakesully123456** [RegalOwl/HyperConomy#89]
This paste shows what happens, I am using hypermerchant and essentials eco with the server.
http://paste.md-5.net/guxurotuma.avrasm
I fixed it by removing the essentials userdata folder, however, it did occur again a few hours later.

**Comment by RegalOwl** [comment]
Could you send me a copy of your Essentials and HyperConomy data?  I can look into it.  The error message is, unfortunately, not very helpful in this case.  Also, are you on the latest version of Essentials and Spigot?
