### ISSUE TITLE
Set Global Server Shop to Have Unlimited Money

### ISSUE THREAD

**Issue by Artige** [RegalOwl/HyperConomy#90]
How do I set the global server shop to have unlimited money? I have "server-shops-have-unlimited-money" set to true but the default server shop account balance still changes and eventually goes empty, preventing players from selling any more items.

Here is my config if needed: http://pastebin.com/jEsq1eJp

I am running this plugin on git-PaperSpigot-7aa4900-62a2169 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

**Comment by RegalOwl** [comment]
I will look into this and get back to you.

**Comment by Artige** [comment]
Thank you very much.

**Comment by RegalOwl** [comment]
I'm still working on this.  I'm just going to rework the code to have a better unlimited balance option for the next update.  The old method was never very good anyway.

**Comment by ZombiePm** [comment]
`shop:
  server-shops-have-unlimited-money: true`

in config.yml
