### ISSUE TITLE
Database corruption

### ISSUE THREAD

**Issue by OLSUS** [RegalOwl/HyperConomy#91]
Got "this" error, and it has deleted all my shops
http://pastebin.com/7UQi0pZt

Hyperconomy 0.975.6
Spigot 1.8.8
Server OS: linux (Ubuntu)

**Comment by remremrem** [comment]
The SQLite database file may have become corrupted, for any number of reasons. If you don't have a backup you may be able to restore the database by following the instructions here: http://www.dosomethinghere.com/2013/02/20/fixing-the-sqlite-error-the-database-disk-image-is-malformed/

Don't forget to back up the database before you attempt to restore it!

**Comment by RegalOwl** [comment]
If you would like an easy to way to repair it on Windows you can [use this script](http://regalowl.net/SQLite_Repair.zip).  Just unzip the file, place your database in the folder and run the script.  When it's done it should generate a file called fixed.db.  Backup your old database and rename the new one HyperConomy.db and try it on your server.  If that doesn't work it's probably beyond repair.  The method the script uses is pretty good though so there is a good chance of fixing it.

**Comment by OLSUS** [comment]
Did not help, but i did not have many shops,so i made new ones. But i will
keep it if something goes wrong with the new one.

Thanks

tir. 26. jan. 2016 kl. 16.52 skrev RegalOwl <notifications@github.com>:
