### ISSUE TITLE
Custom items not working

### ISSUE THREAD

**Issue by Blackyvk** [RegalOwl/HyperConomy#92]
I was trying to open a "banner shop" with customized banners name and lore

1. got the banner using `give Tblack 425 1 0 {BlockEntityTag:{Base:1,Patterns:[{Pattern:cr,Color:11},{Pattern:bo,Color:11},{Pattern:lud,Color:1},{Pattern:rd,Color:1},{Pattern:cre,Color:11},{Pattern:sc,Color:11},{Pattern:bs,Color:1}]}}`
2. I edited these items name and lore with [this plugin](https://www.spigotmc.org/resources/epicrename.4341/)  
3. Added to the shop with /additem custombanner1 3500 

but then, when I sell any or just the normal banners to a frameshop "/frameshop custombanner1" it buys them anyway.

Other problem

adding custom heads like

`give Tblack 397 1 3 {display:{Name:"Cauldron"},SkullOwner:{Id:3758d81b-4cd3-f01e-7606-9ca30082eef4,Properties:{textures:[{Value:eyJ0aW1lc3RhbXAiOjE0MzUwMTk5MDU5NjUsInByb2ZpbGVJZCI6IjUwNzk4YjJhN2QxYjQxYTRiNmFlYzRiNWUwOWJjMTcxIiwicHJvZmlsZU5hbWUiOiJFbHN3ZXlyIiwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzFiMmY2ZmFmMWI5OWFjMzhkNTJiMWM3YmM0OWViNzkxYzY3MDU0MzM3ZDQ0ZDgzZDY2YWRlY2I1MGYzNzUifX19 }]}}}`

doesn't work either, you add the custom head it buys it and when you buy it back it comes as a steve head.

**Comment by RegalOwl** [comment]
Thanks for the report.  I'll do some testing.

**Comment by RegalOwl** [comment]
The first issue you're having I can't reproduce.  Try running the latest dev build.  It may fix the issue.  Using the latest dev build I generated the item as you did, added it to HyperConomy, and then traded it with a frame shop.  The frame shop did not allow me to sell or buy regular banners.

Unfortunately the Bukkit/Spigot API doesn't directly allow the manipulation of item properties/textures as is required to generate the second item.  I'll keep watching this and add this ability when it becomes available.  If it's not added anytime soon I might consider adding it anyway, but it would make HyperConomy harder to support and more likely to break during upgrades.

**Comment by Blackyvk** [comment]
Thanks the banners worked with the dev build, dont worry about the heads if it could break hyperconomy, maybe it could work easily if you add the ability to sell commands, just sell not buy the items generated by it.
