### ISSUE TITLE
Named Firework Stars glitch with chest shops

### ISSUE THREAD

**Issue by Kynrasian** [RegalOwl/HyperConomy#98]
I couldn't find a ticket for this issue, but it seems that named firework stars allow players to interact with chest shops without performing the transaction. Even a firework star named at an anvil will suffice. I'm at wits end, and I apologise if I've missed something.

    Buy shops can be bought from without paying.
    Sell shops can be sold to without being paid.
    Trade shops can be bought from and sold to but only items already in the chest can be sold to it. No money is exchanged.

Reproduction steps:

    Have someone else create a chest shop
    Name a firework star
    Attempt to remove or add items according to what kind of chest it is.
    Profit, literally.

I hope this has been helpful of me.

Edit: added an error message that was appearing on the console.

[Hyperconomy error.txt](https://github.com/RegalOwl/HyperConomy/files/123529/Hyperconomy.error.txt)

**Comment by RegalOwl** [comment]
I apologize for the delay.  This is fixed in the latest build.  Thanks for the report.
